I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 18, in script
    scene background_video_rakpart room
Exception: Image 'background_video_rakpart' does not accept attributes 'room'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 18, in script
    scene background_video_rakpart room
  File "renpy/ast.py", line 1328, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 744, in show
    if not base.find_target() and renpy.config.missing_show:
  File "renpy/display/image.py", line 409, in find_target
    self.target = target._duplicate(a)
  File "renpy/display/core.py", line 390, in _duplicate
    args.extraneous()
  File "renpy/display/core.py", line 271, in extraneous
    " ".join(self.args),
Exception: Image 'background_video_rakpart' does not accept attributes 'room'.

Windows-10-10.0.19041
Ren'Py 7.4.10.2178
eastern_medicine_project 1.0
Wed Nov 17 00:27:03 2021
