I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 45, in script
    menu what_next:
  File "game/script.rpy", line 49, in <module>
    "go to party" if high_on_cocaine:
NameError: name 'high_on_cocaine' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 45, in script
    menu what_next:
  File "renpy/ast.py", line 1688, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "renpy/exports.py", line 1028, in menu
    condition = renpy.python.py_eval(condition)
  File "renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 49, in <module>
    "go to party" if high_on_cocaine:
NameError: name 'high_on_cocaine' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.10.2178
eastern_medicine_project 1.0
Wed Nov 17 01:10:01 2021
